### ISSUE TITLE
Including module breaks <ui-view> rendering

### ISSUE THREAD

**Issue by Mattnmoore** [oldtimeguitarguy/angular-middleware#1]
When I include the module, all of my states stop rendering their templates. There are no errors in the console either. 

```
angular.module('app.core', ['ngCookies', 'ui.router', 'ui.router.middleware']);
```

**Comment by karlhepler** [comment]
Have you defined any middleware and passed them into your routes?

**Comment by Mattnmoore** [comment]
Yeah I defined a simple middleware that just calls `this.next();` and still nothing. But even so, should it stop rendering all routes just by including the module?

**Comment by karlhepler** [comment]
It shouldn't. I'll take a look and try to see what's going on.

**Comment by karlhepler** [comment]
I'm thinking it might be the minified version causing problems - it's the main file referenced in package.json & bower.json. I'm noticing an issue on my end when I use it as well. Please give the non-minified version a try and I'll see if I can stamp out this issue.

**Comment by karlhepler** [comment]
Matt - I did some work, hoping to resolve this issue... that being said - I wasn't able to replicate the exact issue. I'm hoping it's fixed, but if not, would you mind sharing your source code with me so I can track it down?

**Comment by Mattnmoore** [comment]
I will try including the non-minified version tonight when I get home from work. If that doesn't work I'll share my code. Thanks for your help! I love the idea of using middleware like this in my Angular app.

**Comment by karlhepler** [comment]
I just threw some code up on plnkr and referenced with links in the readme under the configuration and examples section. I'm using the latest minified code in plnkr and it's working there. I'll stand by - just let me know how it's working on your end, but I think the issue is cleared up.

**Comment by karlhepler** [comment]
Haven't heard anything in a bit - assuming fixed on your end. I'm going to go ahead and close the issue, and will re-open if necessary.

**Comment by RogerQuiros** [comment]
Same issue, doesn't work at all, i have nothing fancy, just included the module, and made the basic config.

**Comment by karlhepler** [comment]
@Rocker506 - Would you mind attaching a zip of a simple project that isn't working? I'm having trouble recreating the issue on my end - it would be helpful to start with something that I know is failing.

**Comment by karlhepler** [comment]
Hey guys - I the issue and _hopefully_ fixed it. I'm currently using it in a project I'm developing, so I'll be testing it as I work. For now, it seems to be working.
