### ISSUE TITLE
package on npmjs is not up to date

### ISSUE THREAD

**Issue by JonathanGuo** [oldtimeguitarguy/angular-middleware#10]
The repo on npm is out of date. 

The redirectTo function in `src/middleware.factory.js` doesn't have `params` and `options` parameters. When install via npm the function has only `route` parameter available.

```
	/**
	 * Redirect to another route
	 *
	 * @returns {void}
	 */
	function redirectTo(route, params, options) {
		middleware.resolution.reject({
			type: "redirectTo",
			route: route,
			params: params,
			options: options
		});
	}
```

**Comment by karlhepler** [comment]
Thanks for letting me know. Version bumped & up on npm.
