### ISSUE TITLE
Supporting ui-router 1.0

### ISSUE THREAD

**Issue by fakingfantastic** [oldtimeguitarguy/angular-middleware#8]
Any plans to support ui-router 1.0 ? They've moved away from the $stateChange\* events in favor of transition hooks: https://github.com/angular-ui/ui-router/releases/tag/1.0.0alpha0

I'm going to try and fork the repo and add support for it

**Comment by karlhepler** [comment]
Have at it. If it doesn't break anything, I'll put it in. Maybe add it as a new router in the routers folder so the old one can still be used.

I've been experimenting with Angular2 quite a bit and I'll probably end up moving towards that instead of adding much more to this.
