### ISSUE TITLE
this.route is undefined

### ISSUE THREAD

**Issue by iulianmids** [oldtimeguitarguy/angular-middleware#9]
Hello,
Inside a middleware function, I tried to access 'this.route' and it gets undefined.
Tried this as saw in at the bottom of the documentation.

Thanks

**Comment by karlhepler** [comment]
Would you mind sharing a snippet code so I can take a look?

**Comment by iulianmids** [comment]
http://pastebin.com/hmbyZQwH

**Comment by karlhepler** [comment]
Thanks. I'll take a look at it as soon as I can.

**Comment by TiTnOuK** [comment]
Hello,
In release 2.1.8 for me, this line is missing in middleware.factory.js : 
```// Store route name in the request
request.route = toRoute.name;
```

**Comment by karlhepler** [comment]
Thanks @TiTnOuK & @iulianmids 

I think the issue was that I neglected to publish the changes to npm. They are up now. Please let me know if this is still an issue & I'll look into it more.
